move queries in service to dataSource
TheChance101/Honey-Mart-Server pull request #28
Opened 2023-06-05 00:35 UTC by Asiasama710

2023-06-05 02:54 UTC, ahmednasserzaza reviewed
Well done , but what about dao that has all Queries , and data source should call that dao and use fubction that make queres and return result using dependency inversion , That's what I think

2023-06-05 02:54 UTC, ahmednasserzaza commented on app/core/src/main/java/com/thechance/core/data/datasource/CategoryDataSourceImp.kt
> +        } ?: throw IdNotFoundException()
We don't need to throw exception here

2023-06-05 02:54 UTC, ahmednasserzaza commented on app/core/src/main/java/com/thechance/core/data/datasource/CategoryDataSourceImp.kt
> +        } ?: throw NoSuchElementException()
and here

2023-06-05 02:54 UTC, ahmednasserzaza commented on app/core/src/main/java/com/thechance/core/data/datasource/MarketDataSourceImp.kt
> +            } ?: throw IdNotFoundException()
throw exception should be in use case not data source

2023-06-05 16:14 UTC, NadaFeteiha requested changes

2023-06-05 16:14 UTC, NadaFeteiha commented on app/core/src/main/java/com/thechance/core/data/datasource/CategoryDataSourceImp.kt
> +        CategoriesTable.select {
remove null "?", market Id will never be null here.

2023-06-05 16:14 UTC, NadaFeteiha commented on app/core/src/main/java/com/thechance/core/data/datasource/CategoryDataSourceImp.kt
> +                categoryId = resultRow[CategoriesTable.id].value,
you can use a mapper. toCategory.

2023-06-05 16:14 UTC, NadaFeteiha commented on app/core/src/main/java/com/thechance/core/data/datasource/CategoryDataSourceImp.kt
> +                    id = productRow[ProductTable.id].value,
use mapper toProduct

2023-06-06 01:41 UTC, NadaFeteiha approved these changes

2023-06-06 01:44 UTC, merged