search-product
TheChance101/Honey-Mart-Server pull request #79
Opened 2023-07-31 20:29 UTC by mahmmedn19

2023-08-07 06:02 UTC, NadaFeteiha requested changes

2023-08-07 06:02 UTC, NadaFeteiha commented on app/api/src/main/java/com/thechance/api/endpoints/Products.kt
> +            get("/search") {
should added under authenticate(API_KEY_AUTHENTICATION) not authenticate(JWT_AUTHENTICATION)
no need to login to search about product

2023-08-07 06:02 UTC, NadaFeteiha commented on app/api/src/main/java/com/thechance/api/endpoints/Products.kt
> +                val query = call.request.queryParameters["q"]?.trim()
prefer to use"query /keyword" rather than "q"

2023-08-07 11:39 UTC, mahmmedn19 commented on app/api/src/main/java/com/thechance/api/endpoints/Products.kt
> +            get("/search") {
I moved this to (API_KEY_AUTHENTICATION) and add validation

2023-08-08 20:39 UTC, NadaFeteiha approved these changes

2023-08-08 20:39 UTC, merged